= Spring Cloud Netflix

include::intro.adoc[]

== Service Discovery: Eureka Clients

Example eureka client:

```
@Configuration
@ComponentScan
@EnableAutoConfiguration
@EnableEurekaClient
@RestController
public class Application {

    @RequestMapping("/")
    public String home() {
        return "Hello world";
    }
    
    public static void main(String[] args) {
        new SpringApplicationBuilder(Application.class).web(true).run(args);
    }

}

```

(i.e. utterly normal Spring Boot app). Configuration is required to locate the Eureka server. Example:

```
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/v2/
      default.defaultZone: http://localhost:8080/v2/
```

The default application name, virtual host and non-secure port are taken from the `Environment` is 
`${spring.application.name}`, `${spring.application.name}.mydomain.net` and `${server.port}` respectively.

== Service Discovery: Eureka Server

Example eureka server:

```
@Configuration
@EnableAutoConfiguration
@EnableEurekaServer
public class Application {

    public static void main(String[] args) {
        new SpringApplicationBuilder(Application.class).web(true).run(args);
    }

}

```

The server has a home page with a UI, and HTTP API endpoints per the
normal Eureka functionality under `/v2/*`.

Eureka (apache -> tomcat) see https://github.com/cfregly/fluxcapacitor/wiki/NetflixOSS-FAQ#eureka-service-discovery-load-balancer[flux capacitor] and https://groups.google.com/forum/?fromgroups#!topic/eureka_netflix/g3p2r7gHnN0[google group discussion].

== Circuit Breaker: Hystrix Clients

Example boot app:

```
@Configuration
@EnableAutoConfiguration
@EnableHystrix
public class Application {

    public static void main(String[] args) {
        new SpringApplicationBuilder(Application.class).web(true).run(args);
    }

}

@Component
public class StoreIntegration {
    @HystrixCommand(fallbackMethod = "defaultStores")
    public Object getStores(Map<String, Object> parameters) {
        //do stuff that might fail
    }

    public Object defaultStores(Map<String, Object> parameters) {
        return /* something useful */;
    }
}

```

== Circuit Breaker: Hystrix Dashboard

=== Turbine

== Declarative REST Client: Feign

Example spring boot app
```
@Configuration
@ComponentScan
@EnableAutoConfiguration
@EnableEurekaClient
public class Application extends FeignConfigurer {
    @Bean
    public StoreClient storeClient() {
        //loadBalance plugs Feign into ribbon.  feign() works without load balancing.
        return loadBalance(StoreClient.class, "http://stores");
    }

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}
```

StoreClient.java
```
public interface StoreClient {
    @RequestMapping(method = RequestMethod.GET, value = "/stores")
    Stores getStores();

    @RequestMapping(method = RequestMethod.POST, value = "/stores/{storeId}", consumes = "application/json")
    Store update(@PathParameter("storeId") Long storeId, Store store);
}
```

== Client Side Load Balancer: Ribbon

Usage of `LoadBalancerClient` directly:

```
public class MyClass {
    @Autowired
    private LoadBalancerClient loadBalancer;

    public void doStuff() {
        ServiceInstance instance = loadBalancer.choose("stores");
        URI storesUri = URI.create(String.format("http://%s:%s", instance.getHost(), instance.getPort()));
        // ... do something with the URI
    }
}
```

Indirect usage via `RestTemplate`.

```
public class MyClass {
    @Autowired
    private RestTemplate restTemplate;

    public String doOtherStuff() {
        String results = restTemplate.getForObject("http://stores/stores", String.class);
        return results;
    }
}
```

== External Configuration: Archaius

== Router and Filter: Zuul

