= Spring Cloud Netflix

include::intro.adoc[]

== Service Discovery: Eureka Clients

Example eureka client:

```
@Configuration
@ComponentScan
@EnableAutoConfiguration
@EnableEurekaClient
@RestController
public class Application {

	@RequestMapping("/")
	public String home() {
		return "Hello world";
	}
	
	public static void main(String[] args) {
		new SpringApplicationBuilder(Application.class).web(true).run(args);
	}

}

```

(i.e. utterly normal Spring Boot app). Configuration is required to locate the Eureka server. Example:

```
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/v2/
      default.defaultZone: http://localhost:8080/v2/
```

The default application name, virtual host and non-secure port are taken from the `Environment` is 
`${spring.application.name}`, `${spring.application.name}.mydomain.net` and `${server.port}` respectively.

== Service Discovery: Eureka Server

Example eureka server:

```
@Configuration
@EnableAutoConfiguration
@EnableEurekaServer
public class Application {

	public static void main(String[] args) {
		new SpringApplicationBuilder(Application.class).web(true).run(args);
	}

}

```

The server has a home page with a UI, and HTTP API endpoints per the
normal Eureka functionality under `/v2/*`.

Eureka (apache -> tomcat) see https://github.com/cfregly/fluxcapacitor/wiki/NetflixOSS-FAQ#eureka-service-discovery-load-balancer[flux capacitor] and https://groups.google.com/forum/?fromgroups#!topic/eureka_netflix/g3p2r7gHnN0[google group discussion].

== Circuit Breaker: Hystrix Clients

== Circuit Breaker: Hystrix Dashboard

=== Turbine

== Declarative REST Client: Feign

== Client Side Load Balancer: Ribbon

== External Configuration: Archaius

== Router and Filter: Zuul

