info:
  component: Turbine Stream
spring:
  application:
    name: turbine
  cloud.stream.bindings:
    turbineStreamInput: springCloudHystrixStream
  jmx:
    default_domain: cloud.turbine.stream

server:
  port: 8990
turbine:
  stream:
    port: 8989
 