### Global gh-pages pre-amble
safe: true
lsi: false
highlighter: rouge
markdown: kramdown
encoding: UTF-8
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]
gems:
  - jekyll-coffeescript
  - jekyll-paginate

### The following properties will change on a project-by-project basis

# Context path in the remote website (usually /<project>), will be prepended to absolute URLs for static resources
baseurl: /spring-cloud-netflix

# Name of the project for display in places like page titles
name: Spring Cloud Netflix

# ID of the project in the metadata API at spring.io (if this is not a
# valid project ID the javascript widgets in the home page will not work)
project: spring-cloud-netflix

# Project github URL
github_repo_url: https://github.com/spring-cloud/spring-cloud-netflix

# Project forum URL
forum: https://stackoverflow.com/questions/tagged/spring-cloud

# If you want to include a custom pom.xml or gradle template set these value to true and add _include files
custom_pom_template: true
custom_gradle_template: true


### The following properties are constant for most projects

main_site_url: https://spring.io
projects_site_url: https://projects.spring.io
questions_url: https://spring.io/questions
