name: Test Release
runs:
  using: composite
  steps:
    - name: Test Release
      shell: bash
      run: ./mvnw --batch-mode --settings release-train-settings.xml clean verify --activate-profiles releaseTrain
