/*
 * Copyright 2016 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.cloud.netflix.hystrix.stream;

import java.util.Map;

import com.netflix.hystrix.contrib.javanica.annotation.HystrixCommand;

import org.junit.runner.RunWith;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cloud.client.circuitbreaker.EnableCircuitBreaker;
import org.springframework.cloud.contract.verifier.messaging.boot.AutoConfigureMessageVerifier;
import org.springframework.cloud.netflix.hystrix.stream.StreamSourceTestBase.TestApplication;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Base class for sensor autogenerated tests (used by Spring Cloud Contract).
 *
 * This bootstraps the Spring Boot application code.
 *
 * @author Marius Bogoevici
 */
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(classes = TestApplication.class)
@AutoConfigureMessageVerifier
public abstract class StreamSourceTestBase {

	@Autowired
	TestApplication application;

	public void createMetricsData() throws Exception {
		application.hello();
	}

	public void assertOrigin(Object input) {
		@SuppressWarnings("unchecked")
		Map<String, Object> origin = (Map<String, Object>) input;
		assertThat(origin.get("host")).isNotNull();
		assertThat(origin.get("port")).isNotNull();
		assertThat(origin.get("serviceId")).isEqualTo("application");
		// TODO: should be server.port?
		assertThat(origin.get("id")).isEqualTo("application:-1");
	}

	public void assertData(Object input) {
		System.err.println(input);
		@SuppressWarnings("unchecked")
		Map<String, Object> data = (Map<String, Object>) input;
		assertThat(data.get("type")).isEqualTo("HystrixCommand");
		// TODO: should be application.hello
		assertThat(data.get("name")).asString().startsWith("application.");
		assertThat(data.get("group")).isNotNull();
		// TODO: should be TestApplication
		// assertThat(data.get("group")).isEqualTo(TestApplication.class.getSimpleName());
	}

	@EnableAutoConfiguration
	@EnableCircuitBreaker
	@RestController
	public static class TestApplication {

		@HystrixCommand
		@RequestMapping("/")
		public String hello() {
			return "Hello World";
		}

		public static void main(String[] args) {
			SpringApplication.run(TestApplication.class, args);
		}

	}
}
