name: Build Release
runs:
  using: composite
  steps:
    - name: Build Release
      shell: bash
      # If we are on Java 8 we need to build the docs zip for jubilee projects so it is distributed as part of the release
      run: |
        if java -version 2>&1 | grep -q '1\.8\.'; then
          ./mvnw --batch-mode --settings release-train-settings.xml clean deploy --activate-profiles releaseTrain,docs -DaltDeploymentRepository="release-train::default::file://$(pwd)/deployment-repository" -Dmaven-deploy-plugin.deployZipUrl="file://$(pwd)/deployment-repository" -Dmaven-deploy-plugin-default.phase=deploy -Dupload-docs-zip.packaging=zip -DskipTests
        else
          ./mvnw --batch-mode --settings release-train-settings.xml clean deploy --activate-profiles releaseTrain -DaltDeploymentRepository="release-train::default::file://$(pwd)/deployment-repository" -DskipTests
        fi